/**
 * 1.0.6 — brainstorm produces commercial-only output.
 *
 * Negative-regression guard against the entire trust-failure class from
 * 1.0.2 through 1.0.5: non-commercial intents (vertical / comparison /
 * problem) generated by the old 4-bucket pipeline routinely failed the
 * downstream commercial-only validator, producing the "recovery panel
 * suggests command that the CLI rejects" loop.
 */

import test from 'node:test';
import assert from 'node:assert';
import {
  INTENT_BUCKETS, OUTPUT_BUCKET_KEYS, TARGET_PER_BUCKET, TARGET_TOTAL_MIN,
  buildBrainstormPrompt, parseBrainstormResponse, validateBrainstormShape,
} from '../lib/init/research/brainstorm.js';

test('INTENT_BUCKETS contains only commercial', () => {
  assert.deepEqual(INTENT_BUCKETS, ['commercial']);
});

test('OUTPUT_BUCKET_KEYS preserves all 4 keys for backward-compat', () => {
  assert.deepEqual(OUTPUT_BUCKET_KEYS, ['commercial', 'problem', 'vertical', 'comparison']);
});

test('TARGET constants: 5 per bucket, ≥5 total', () => {
  assert.equal(TARGET_PER_BUCKET, 5);
  assert.equal(TARGET_TOTAL_MIN, 5);
});

test('buildBrainstormPrompt asks for exactly 5 commercial queries (not 4 buckets)', () => {
  const prompt = buildBrainstormPrompt({
    brand: 'acme', domain: 'acme.com',
    site: { lang: 'en', title: 'Acme' },
    categoryDescription: 'voice form filling',
  });
  assert.match(prompt, /exactly 5 UNBRANDED COMMERCIAL/);
  // Output schema in the prompt has only `commercial` key
  assert.match(prompt, /"commercial":\s*\[/);
  // Must NOT instruct the LLM to generate other bucket types
  assert.doesNotMatch(prompt, /"problem":\s*\[/);
  assert.doesNotMatch(prompt, /"vertical":\s*\[/);
  assert.doesNotMatch(prompt, /"comparison":\s*\[/);
  assert.doesNotMatch(prompt, /"informational":\s*\[/);
});

test('validateBrainstormShape: 5 commercial → shape with empty non-commercial buckets', () => {
  const parsed = {
    commercial: [
      'best voice form filling tools 2026',
      'top voice form widgets for SaaS',
      'voice form filling services for healthcare',
      'enterprise voice form solutions',
      'commercial voice form automation platforms',
    ],
  };
  const result = validateBrainstormShape(parsed);
  assert.equal(result.flat.length, 5, 'flat array contains all 5 commercial queries');
  assert.equal(result.totalAcross, 5);
  // Backward-compat: all four bucket keys present, only commercial has entries.
  assert.equal(result.buckets.commercial.length, 5);
  assert.deepEqual(result.buckets.problem, []);
  assert.deepEqual(result.buckets.vertical, []);
  assert.deepEqual(result.buckets.comparison, []);
});

test('NEGATIVE REGRESSION: every flat entry has intent==commercial', () => {
  const parsed = {
    commercial: [
      'best X 2026', 'top X for Y', 'X consultants for Z',
      'X tools for industry', 'X services for SMB',
    ],
  };
  const result = validateBrainstormShape(parsed);
  assert.ok(result.flat.every(c => c.intent === 'commercial'),
    'flat array must contain ONLY commercial-intent entries (the 1.0.6 contract)');
});

test('validateBrainstormShape: fewer than 5 valid queries → throws', () => {
  const parsed = { commercial: ['only one', 'two only'] };
  assert.throws(
    () => validateBrainstormShape(parsed),
    /Brainstorm produced only 2 commercial queries — need at least 5/,
  );
});

test('validateBrainstormShape: non-commercial keys in input ignored', () => {
  // Even if the LLM ignores instructions and produces other-bucket entries,
  // only `commercial` is read. The other buckets stay empty in output.
  const parsed = {
    commercial: ['query one', 'query two', 'query three', 'query four', 'query five'],
    problem: ['why-is-thing-broken-ignored', 'how-fix-ignored'],
    vertical: ['form for healthcare ignored'],
  };
  const result = validateBrainstormShape(parsed);
  assert.equal(result.flat.length, 5);
  assert.deepEqual(result.buckets.problem, []);
  assert.deepEqual(result.buckets.vertical, []);
});

test('parseBrainstormResponse handles markdown-fenced JSON', () => {
  const wrapped = '```json\n{"commercial":["a","b","c","d","e"]}\n```';
  const parsed = parseBrainstormResponse(wrapped);
  assert.equal(parsed.commercial.length, 5);
});
